version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - pxm-data:/data
      - pxm-letsencrypt:/etc/letsencrypt
volumes:
    pxm-data:
      driver: local
    pxm-letsencrypt:
      driver: local